/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    FinalPage: typeof import('./src/components/FinalPage.vue')['default']
    IntroPage: typeof import('./src/components/IntroPage.vue')['default']
    IntroPageFinal: typeof import('./src/components/IntroPageFinal.vue')['default']
    IntroPageFirst: typeof import('./src/components/IntroPageFirst.vue')['default']
    IntroPageLast: typeof import('./src/components/IntroPageLast.vue')['default']
    IntroPageSecond: typeof import('./src/components/IntroPageSecond.vue')['default']
    IntroPageThird: typeof import('./src/components/IntroPageThird.vue')['default']
    PageContainer: typeof import('./src/components/PageContainer.vue')['default']
    TheRightMenu: typeof import('./src/components/TheRightMenu.vue')['default']
  }
}
